### ISSUE TITLE
[Feature request] filter file endings / names

### ISSUE THREAD

**Issue by Alistair1231** [jreisinger/ghrel#1]
Awesome tool! Thanks!
Could you add support for name/file-ending filtering?

I'm thinking of something like:

```
ghrel AppImage/pkg2appimage --filter *.AppImage
```
or

```
ghrel AppImage/pkg2appimage --extension AppImage
```
 
Also, installing via go used to work, but doesn't anymore? I had to install manually by downloading the tar file and copying the binary to `/usr/bin`

**Comment by jreisinger** [comment]
Hi @Auncaughbove17, thanks for interest and appreciation!

I tried out the installation via go (in a container), and it's working for me:

```bash
$ docker run --rm -it golang:1.18
root@efc5fd68eaa7:/go# go install github.com/jreisinger/ghrel@latest
go: downloading github.com/jreisinger/ghrel v0.3.1
root@efc5fd68eaa7:/go# ghrel jreisinger/ghrel
downloading release files     OK (6)
verifying checksums           OK (5)
```

As for the feature request, I plan to have a look at it.

**Comment by jreisinger** [comment]
OK, I think the feature is not worth the added complexity. When I try out your example, I get the two files pretty quickly. And I can pick the correct one easily. I see no need for filtering.

```sh
$ ghrel AppImage/pkg2appimage
downloading release files     OK (2)
verifying checksums           OK (0)
$ ls
pkg2appimage-1807-x86_64.AppImage  pkg2appimage-1807-x86_64.AppImage.zsync
```

**Comment by hongkongkiwi** [comment]
It really depends on the package your using, some have very large release files. It is a bit dumb to download all of them. I also want a way to filter the files.

**Comment by jreisinger** [comment]
@hongkongkiwi can you provide the repository you have in mind? And what files would you like to filter out?

**Comment by Alistair1231** [comment]
I was just thinking of using this tool in some automated script for updating an application, and thought it was silly that I had to download all kinds of files just to delete most of them afterwards.
An example of large amounts of large-ish files would be [brave/brave-browser](https://github.com/brave/brave-browser/releases/) and [git-for-windows/git](https://github.com/git-for-windows/git/releases/) off the top of my head.
In the example of Brave, I would have to download 40 files just to delete 39 of them.

**Comment by jreisinger** [comment]
Ok, I see. So what would be the idea, something like

```
ghrel -p '*linux*amd64*' # download just files matching the shell name pattern
```

or

```
ghrel -r 'linux.*amd64\.tgz$' # download just files matching the regexp
```

?

**Comment by jreisinger** [comment]
Ok, I implemented the first variant. Please see v0.4.0.

**Comment by Alistair1231** [comment]
Yeah full on regex seems overkill and is probably not necessary in most use-cases. 
Great stuff. Thanks!
