### ISSUE TITLE
[Feature request] export released time

### ISSUE THREAD

**Issue by Doddddd** [jreisinger/ghrel#2]
`ghrel -d jreisinger/ghrel`
`Released on:   2023-03-14 12:49:38 +0800`
Advanced
`ghrel -date=iso8601 jreisinger/ghrel`
`Released on:   2023-03-14 12:49:38 +0800`

**Comment by jreisinger** [comment]
Hi @Doddddd. Why do you need this feature and how do you plan to use it?

**Comment by Doddddd** [comment]
> Hi @Doddddd. Why do you need this feature and how do you plan to use it?

Some file names don't contain the version number, and I want to rename it with the release date.

**Comment by jreisinger** [comment]
Would this be useful?

```
> ghrel -l jreisinger/ghrel
Asset                             Updated     Size     Download count
-----                             -------     ----     --------------
checksums.txt                     2023-02-24  976      2
ghrel_0.5.3_darwin_amd64.tar.gz   2023-02-24  2192333  5
ghrel_0.5.3_darwin_arm64.tar.gz   2023-02-24  2106681  2
ghrel_0.5.3_linux_386.tar.gz      2023-02-24  2024618  4
ghrel_0.5.3_linux_amd64.tar.gz    2023-02-24  2137362  25
ghrel_0.5.3_linux_arm64.tar.gz    2023-02-24  1969924  2
ghrel_0.5.3_linux_armv6.tar.gz    2023-02-24  2000417  2
ghrel_0.5.3_windows_386.tar.gz    2023-02-24  2040730  4
ghrel_0.5.3_windows_amd64.tar.gz  2023-02-24  2105538  13
ghrel_0.5.3_windows_arm64.tar.gz  2023-02-24  1942813  2
ghrel_0.5.3_windows_armv6.tar.gz  2023-02-24  1993760  2
```

**Comment by Doddddd** [comment]
> 这会有用吗？
> 
> ```
> > ghrel -l jreisinger/ghrel
> Asset                             Updated     Size     Download count
> -----                             -------     ----     --------------
> checksums.txt                     2023-02-24  976      2
> ghrel_0.5.3_darwin_amd64.tar.gz   2023-02-24  2192333  5
> ghrel_0.5.3_darwin_arm64.tar.gz   2023-02-24  2106681  2
> ghrel_0.5.3_linux_386.tar.gz      2023-02-24  2024618  4
> ghrel_0.5.3_linux_amd64.tar.gz    2023-02-24  2137362  25
> ghrel_0.5.3_linux_arm64.tar.gz    2023-02-24  1969924  2
> ghrel_0.5.3_linux_armv6.tar.gz    2023-02-24  2000417  2
> ghrel_0.5.3_windows_386.tar.gz    2023-02-24  2040730  4
> ghrel_0.5.3_windows_amd64.tar.gz  2023-02-24  2105538  13
> ghrel_0.5.3_windows_arm64.tar.gz  2023-02-24  1942813  2
> ghrel_0.5.3_windows_armv6.tar.gz  2023-02-24  1993760  2
> ```

Sure, thanks for your job!

**Comment by Doddddd** [comment]
> Would this be useful?
> 
> ```
> > ghrel -l jreisinger/ghrel
> Asset                             Updated     Size     Download count
> -----                             -------     ----     --------------
> checksums.txt                     2023-02-24  976      2
> ghrel_0.5.3_darwin_amd64.tar.gz   2023-02-24  2192333  5
> ghrel_0.5.3_darwin_arm64.tar.gz   2023-02-24  2106681  2
> ghrel_0.5.3_linux_386.tar.gz      2023-02-24  2024618  4
> ghrel_0.5.3_linux_amd64.tar.gz    2023-02-24  2137362  25
> ghrel_0.5.3_linux_arm64.tar.gz    2023-02-24  1969924  2
> ghrel_0.5.3_linux_armv6.tar.gz    2023-02-24  2000417  2
> ghrel_0.5.3_windows_386.tar.gz    2023-02-24  2040730  4
> ghrel_0.5.3_windows_amd64.tar.gz  2023-02-24  2105538  13
> ghrel_0.5.3_windows_arm64.tar.gz  2023-02-24  1942813  2
> ghrel_0.5.3_windows_armv6.tar.gz  2023-02-24  1993760  2
> ```

Sure, thanks for your job!

**Comment by jreisinger** [comment]
Implemented.
