### ISSUE TITLE
[Feature Requests] List Versions and Gitlab Support.

### ISSUE THREAD

**Issue by dCo3lh0** [jreisinger/ghrel#3]
I dont know if its possible for you, but if you could list versions, and download by version, like a parameter option, sometimes you want to download the stable one not the continuous version.

And another feature is it possible this tool works with gitlab as well? i know its fewer but there is  dozens (thousands) of projects done in gitlab as the main repository, so they release their packages there. Awesome tool, i was missing something like this.

**Comment by jreisinger** [comment]
Thanks.

The tool is called ghrel meaning GitHub release. So it wouldn't make sense to support also GitLab.

To download not only the latest but any release would complicate the code and the user interface. I think most people don't need this feature so it's not worth the complexity.
