### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by madkarmaa** [jreisinger/ghrel#5]
![image](https://github.com/jreisinger/ghrel/assets/100418457/1e7b6bd7-b442-4fb2-825b-b2ec5f052117)

https://www.virustotal.com/gui/file/965a0e4fc0ed10c7f1074799331c1c8e7fb746c67180731dbb9186c41d039fa8?nocache=1

**Comment by jreisinger** [comment]
Yeah, I would think so. I don't know why those 2 out of 70 vendors "think" the file is malicious ... Anyway, thanks for letting me know 👍
